# ---------------------------------
# LGMC Simulation Input Conditions
# ---------------------------------
# Simulation Mode
mode: 'nucleation'      # 'nucleation' or 'wetting [not yet]'

# For system initialization
r: 10                   # size of lattice(length = 2*r + 1), default: 10
conc: 0.1               # concentration of particle in lattice, default: 0.1
sys: 'homo'             # nulceation system, 'homo' or 'hete'

# For dynamics,
dynamics: 'kawasaki'    # the Method of Dynamics, 'kawasaki' or 'glauber [not yet]'
pbc: [True, True, True] # PBC of each axis [x, y, z], default: [True, True, True]
temp: 0.2               # the dimensionless temperature (T/Tc), default: 0.1
eps_NN: 1.0             # the dimensionless epsilon_nn, default: 1.0
eps_s: 0.1              # the dimensionless epsilon_surf, default: 0.0
mu: None                # the coexistence chemcial potential, default: None

# For MC run,
n_steps: 10000          # # of MC steps, default: 1000
n_sample: 100           # # of sampling interval steps, default: 100
verbose: True           # Checking or Not [tqdm], default: False
save_dir: 'mc_out'      # Directory to save lattice [.xyz], default: './mc_out'

# logging
# log: 'log.log'          # log file name, default: {mode}_{sys}_R{r}c{conc}t{temp}_{dynamics}.log




